### ISSUE TITLE
请问作者用于抓包俺来也的工具是什么？

### ISSUE THREAD

**Issue by jiumao2** [andywang425/ImComingMonitor#1]
我试了fiddler，但证书似乎与俺来也不兼容，无法抓包https

**Comment by andywang425** [comment]
我用的就是fiddler，先给你的安卓手机安装xposed框架，再安装justTrustMe模块，就可以抓包了。  
之后可能会写一下相关的教程，或者想办法根据商家名称自动获取shop_id。

**Comment by jiumao2** [comment]
可以工作了，谢谢！
